# Generated by Django 5.2.1 on 2025-05-10 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='These',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('domaine', models.CharField(choices=[('Cardiologie', 'Cardiologie'), ('Neurologie', 'Neurologie'), ('Pédiatrie', 'Pédiatrie'), ('Chirurgie', 'Chirurgie')], max_length=255)),
                ('description', models.TextField()),
                ('motivation', models.TextField()),
                ('encadreur', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='theses/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Rejeté', 'Rejeté')], default='En attente', max_length=20)),
                ('approuve_par_comite', models.BooleanField(default=False)),
                ('date_soutenance', models.DateField(blank=True, null=True)),
                ('rapport_intermediaire', models.FileField(blank=True, null=True, upload_to='theses/rapport_intermediaire/')),
                ('statut_rapport', models.CharField(choices=[('Non assigné', 'Non assigné'), ('Assigné', 'Assigné'), ('Évalué', 'Évalué')], default='Non assigné', max_length=50)),
                ('date_rapport_intermediaire', models.DateTimeField(blank=True, null=True)),
                ('rapporteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_assigned', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
