# Generated by Django 5.1.5 on 2025-05-11 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_notification_these'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RapportFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='rapports_finals/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('these', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_finals', to='gestion.these')),
            ],
        ),
        migrations.CreateModel(
            name='RapportIntermediaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='rapports_intermediaires/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('these', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_intermediaires', to='gestion.these')),
            ],
        ),
    ]
