# Generated by Django 5.1.5 on 2025-05-12 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_historiqueaction_rapportfinal_rapportintermediaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('these', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.these')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('rapporteur', 'Rapporteur'), ('examinateur', 'Examinateur'), ('president', 'Président'), ('redacteur', 'Rédacteur')], max_length=20)),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('grille_evaluation', models.FileField(blank=True, null=True, upload_to='grilles/')),
                ('decision', models.CharField(blank=True, max_length=50, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('these', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.these')),
            ],
            options={
                'unique_together': {('these', 'professeur', 'role')},
            },
        ),
    ]
