# Generated by Django 5.1.5 on 2025-05-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_comite_commentaire_affectation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('professeur', 'Professeur'), ('comite', 'Comité')], max_length=20)),
                ('promotion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
