# Generated by Django 5.1.5 on 2025-05-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_demandeutilisateur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='date',
            new_name='date_creation',
        ),
        migrations.AddField(
            model_name='notification',
            name='date_lecture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='lien',
            field=models.URLField(blank=True, null=True),
        ),
    ]
