# Generated by Django 5.1.5 on 2025-05-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='date_creation',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='date_lecture',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='lien',
        ),
    ]
