# Generated by Django 5.1.5 on 2025-05-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_rename_date_notification_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='these',
            name='commentaire_rejet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
