# Generated by Django 5.1.5 on 2025-05-15 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_these_grille_evaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportintermediaire',
            name='fichier',
            field=models.FileField(upload_to='rapport_intermediaires/'),
        ),
        migrations.AlterField(
            model_name='rapportintermediaire',
            name='these',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapport_intermediaires', to='gestion.these'),
        ),
    ]
