# Generated by Django 5.1.5 on 2025-05-15 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_rapportintermediaire_fichier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportintermediaire',
            name='these',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_intermediaires', to='gestion.these'),
        ),
    ]
