# Generated by Django 5.1.5 on 2025-05-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_rapportintermediaire_these'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='these',
            name='rapport_intermediaire',
        ),
    ]
