# Generated by Django 5.1.5 on 2025-05-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_rapportintermediaire_these'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportintermediaire',
            name='fichier',
            field=models.FileField(upload_to='rapports_intermediaires/'),
        ),
    ]
